2023-01-31 16:31:31.629 | DEBUG    | hcaptcha_challenger._solutions.kernel:_request_asset:320 - Downloading objects.yaml from https://raw.githubusercontent.com/QIN2DIM/hcaptcha-challenger/main/src/objects.yaml
2023-01-31 16:31:31.768 | DEBUG    | hcaptcha_challenger._solutions.kernel:request_assets:148 - Pulling AssetsObject from https://api.github.com/repos/QIN2DIM/hcaptcha-challenger/releases
2023-01-31 16:31:31.850 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2023-01-31 16:31:32.199 | DEBUG    | hcaptcha_challenger._solutions.kernel:request_assets:148 - Pulling AssetsObject from https://api.github.com/repos/QIN2DIM/hcaptcha-challenger/releases
2023-01-31 16:31:32.281 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2023-01-31 16:31:33.838 | DEBUG    | hcaptcha_challenger._solutions.kernel:request_assets:148 - Pulling AssetsObject from https://api.github.com/repos/QIN2DIM/hcaptcha-challenger/releases
2023-01-31 16:31:33.921 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2023-01-31 16:31:33.931 | INFO     | services.deploy:job_loop_claim:104 - >> STARTUP [AwesomeScheduler] SynergyTunnel - version=0.4.4-dev Pattern=False
2023-01-31 16:31:34.960 | INFO     | services.bricklayer.core:refresh_ctx_cookies:691 - >> MATCH [__context__] 🎮启动挑战者上下文
2023-01-31 16:31:35.011 | INFO     | services.bricklayer.core:login:491 - >> MATCH [CookieManager] 刷新令牌
2023-01-31 16:31:46.225 | INFO     | services.bricklayer.core:login:526 - >> MATCH [CookieManager] 实体信息注入完毕
2023-01-31 16:31:46.225 | INFO     | services.bricklayer.core:fall_in_captcha_login:36 - >> ARMOR [ArmorUtils] 正在检测隐藏在登录界面的人机挑战...
2023-01-31 16:31:48.442 | DEBUG    | hcaptcha_challenger.core:log:317 - >> Challenge [ArmorCaptcha] Get label - label=「雏菊」
2023-01-31 16:31:48.442 | DEBUG    | hcaptcha_challenger.core:log:317 - >> Challenge [ArmorCaptcha] 正在编排索引
2023-01-31 16:31:49.011 | DEBUG    | hcaptcha_challenger.core:log:317 - >> Challenge [ArmorCaptcha] 正在下载挑战图片
2023-01-31 16:31:50.037 | DEBUG    | hcaptcha_challenger.core:log:317 - >> Challenge [ArmorCaptcha] Download challenge images - timeit=1.03s
2023-01-31 16:31:50.039 | DEBUG    | hcaptcha_challenger._solutions.kernel:request_assets:148 - Pulling AssetsObject from https://api.github.com/repos/QIN2DIM/hcaptcha-challenger/releases
2023-01-31 16:31:50.136 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2023-01-31 16:31:50.277 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1837), thread 'MainThread' (140228589665344):
Traceback (most recent call last):
  File "/home/runner/work/free/free/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/home/runner/work/free/free/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/free/free/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/free/free/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/free/free/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/free/free/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/free/free/epic/src/services/bricklayer/core.py", line 708, in refresh_ctx_cookies
    resp = self.armor.anti_hcaptcha(page, window="login", recur_url=recur_url)
  File "/home/runner/work/free/free/epic/src/services/bricklayer/core.py", line 267, in anti_hcaptcha
    self.challenge(frame_challenge, model=model)
  File "/home/runner/work/free/free/epic/src/services/bricklayer/core.py", line 125, in challenge
    result = model.solution(img_stream=data, label=self.label_alias[self.label])
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 63, in solution
    return self.classifier(img_stream, feature_filters=None)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 54, in classifier
    raise ResourceWarning(_err_prompt)  # maybe mercy
ResourceWarning: 
            The remote network does not exist or the local cache has expired.
            1. Check objects.yaml for typos | model=daisy.onnx;
            2. Restart the program after deleting the local cache | dir=datas/models/_assets;
            
